name: Run job in Docker container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-node-app .

    - name: Run Docker container
      run: docker run -p 8080:8080 -d --name my-node-app-container my-node-app

    - name: Print Docker container logs
      run: docker logs my-node-app-container
